// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	IssuedAt  time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserAgent string
	Ip        string
}

type Session struct {
	ID            uuid.UUID
	SessionCode   string
	SessionName   string
	CreatorUserID uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Status        sql.NullString
}

type SessionItem struct {
	ID              uuid.UUID
	SessionID       uuid.UUID
	ItemTitle       string
	ItemDescription sql.NullString
	ImageUrl        sql.NullString
	SourceType      string
	SourceID        sql.NullString
	Metadata        pqtype.NullRawMessage
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AddedByUserID   uuid.UUID
}

type SessionParticipant struct {
	UserID    uuid.UUID
	SessionID uuid.UUID
	JoinedAt  time.Time
	Status    sql.NullString
}

type User struct {
	ID                uuid.UUID
	Username          string
	Email             string
	PasswordHash      string
	PasswordChangedAt sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         sql.NullTime
}
