services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: optio
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
